// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateBook implements createBook operation.
	//
	// Создать книгу.
	// Сохраняет новую книгу в хранилище в памяти и
	// назначает идентификатор.
	//
	// POST /books
	CreateBook(ctx context.Context, req *NewBook) (*Book, error)
	// DeleteBook implements deleteBook operation.
	//
	// Удалить книгу.
	// Удаляет одну книгу из хранилища в памяти.
	//
	// DELETE /books/{id}
	DeleteBook(ctx context.Context, params DeleteBookParams) error
	// GetBook implements getBook operation.
	//
	// Получить книгу.
	// Читает одну книгу по идентификатору из хранилища в
	// памяти.
	//
	// GET /books/{id}
	GetBook(ctx context.Context, params GetBookParams) (*Book, error)
	// ListBooks implements listBooks operation.
	//
	// Получить список книг.
	// Возвращает все книги из хранилища в памяти.
	//
	// GET /books
	ListBooks(ctx context.Context) ([]Book, error)
	// UpdateBook implements updateBook operation.
	//
	// Обновить книгу.
	// Заменяет одну существующую книгу в хранилище в
	// памяти.
	//
	// PUT /books/{id}
	UpdateBook(ctx context.Context, req *NewBook, params UpdateBookParams) (*Book, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
