// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateBook implements createBook operation.
	//
	// Create a book.
	// Stores a new book in in-memory storage and assigns an identifier.
	//
	// POST /books
	CreateBook(ctx context.Context, req *NewBook) (*Book, error)
	// DeleteBook implements deleteBook operation.
	//
	// Delete a book.
	// Removes one book from in-memory storage.
	//
	// DELETE /books/{id}
	DeleteBook(ctx context.Context, params DeleteBookParams) error
	// GetBook implements getBook operation.
	//
	// Get a book.
	// Reads one book by identifier from in-memory storage.
	//
	// GET /books/{id}
	GetBook(ctx context.Context, params GetBookParams) (*Book, error)
	// ListBooks implements listBooks operation.
	//
	// List books.
	// Returns all books from in-memory storage.
	//
	// GET /books
	ListBooks(ctx context.Context) ([]Book, error)
	// UpdateBook implements updateBook operation.
	//
	// Update a book.
	// Replaces one existing book in in-memory storage.
	//
	// PUT /books/{id}
	UpdateBook(ctx context.Context, req *NewBook, params UpdateBookParams) (*Book, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
