// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateBook implements createBook operation.
//
// Create a book.
// Stores a new book in in-memory storage and assigns an identifier.
//
// POST /books
func (UnimplementedHandler) CreateBook(ctx context.Context, req *NewBook) (r *Book, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBook implements deleteBook operation.
//
// Delete a book.
// Removes one book from in-memory storage.
//
// DELETE /books/{id}
func (UnimplementedHandler) DeleteBook(ctx context.Context, params DeleteBookParams) error {
	return ht.ErrNotImplemented
}

// GetBook implements getBook operation.
//
// Get a book.
// Reads one book by identifier from in-memory storage.
//
// GET /books/{id}
func (UnimplementedHandler) GetBook(ctx context.Context, params GetBookParams) (r *Book, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBooks implements listBooks operation.
//
// List books.
// Returns all books from in-memory storage.
//
// GET /books
func (UnimplementedHandler) ListBooks(ctx context.Context) (r []Book, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateBook implements updateBook operation.
//
// Update a book.
// Replaces one existing book in in-memory storage.
//
// PUT /books/{id}
func (UnimplementedHandler) UpdateBook(ctx context.Context, req *NewBook, params UpdateBookParams) (r *Book, _ error) {
	return r, ht.ErrNotImplemented
}
