// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateBook implements createBook operation.
//
// Создать книгу.
// Сохраняет новую книгу в хранилище в памяти и
// назначает идентификатор.
//
// POST /books
func (UnimplementedHandler) CreateBook(ctx context.Context, req *NewBook) (r *Book, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBook implements deleteBook operation.
//
// Удалить книгу.
// Удаляет одну книгу из хранилища в памяти.
//
// DELETE /books/{id}
func (UnimplementedHandler) DeleteBook(ctx context.Context, params DeleteBookParams) error {
	return ht.ErrNotImplemented
}

// GetBook implements getBook operation.
//
// Получить книгу.
// Читает одну книгу по идентификатору из хранилища в
// памяти.
//
// GET /books/{id}
func (UnimplementedHandler) GetBook(ctx context.Context, params GetBookParams) (r *Book, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBooks implements listBooks operation.
//
// Получить список книг.
// Возвращает все книги из хранилища в памяти.
//
// GET /books
func (UnimplementedHandler) ListBooks(ctx context.Context) (r []Book, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateBook implements updateBook operation.
//
// Обновить книгу.
// Заменяет одну существующую книгу в хранилище в
// памяти.
//
// PUT /books/{id}
func (UnimplementedHandler) UpdateBook(ctx context.Context, req *NewBook, params UpdateBookParams) (r *Book, _ error) {
	return r, ht.ErrNotImplemented
}
