// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/Book
type Book struct {
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	Author string `json:"author"`
}

// GetID returns the value of ID.
func (s *Book) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Book) GetTitle() string {
	return s.Title
}

// GetAuthor returns the value of Author.
func (s *Book) GetAuthor() string {
	return s.Author
}

// SetID sets the value of ID.
func (s *Book) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Book) SetTitle(val string) {
	s.Title = val
}

// SetAuthor sets the value of Author.
func (s *Book) SetAuthor(val string) {
	s.Author = val
}

// DeleteBookNoContent is response for DeleteBook operation.
type DeleteBookNoContent struct{}

// Ref: #/components/schemas/NewBook
type NewBook struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}

// GetTitle returns the value of Title.
func (s *NewBook) GetTitle() string {
	return s.Title
}

// GetAuthor returns the value of Author.
func (s *NewBook) GetAuthor() string {
	return s.Author
}

// SetTitle sets the value of Title.
func (s *NewBook) SetTitle(val string) {
	s.Title = val
}

// SetAuthor sets the value of Author.
func (s *NewBook) SetAuthor(val string) {
	s.Author = val
}
