// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateBookOperation OperationName = "CreateBook"
	DeleteBookOperation OperationName = "DeleteBook"
	GetBookOperation    OperationName = "GetBook"
	ListBooksOperation  OperationName = "ListBooks"
	UpdateBookOperation OperationName = "UpdateBook"
)
